# Generated by Django 3.2 on 2021-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
