# Generated by Django 3.2 on 2021-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='ROI',
            field=models.IntegerField(max_length=70),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_of_loan',
            field=models.IntegerField(max_length=70),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanamt',
            field=models.IntegerField(max_length=70),
        ),
    ]
