# Generated by Django 3.2 on 2021-05-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20210513_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='ROI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_of_loan',
            field=models.IntegerField(default=1000001),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanamt',
            field=models.IntegerField(default=(100021, 23, 422)),
            preserve_default=False,
        ),
    ]
